
version: '3'
services:
  ultra:
    build: .
    image: rajashekaradukani/ultra
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ultraDB
      DATABASE_PORT:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgrespw
      JWT_SECRET: Rpfgl5eigJSEwsI5/MLjAQ==
      ADMIN_JWT_SECRET: mJ5OtNqsY2Ws8/Y1qLq3BA==
      APP_KEYS: htLOJrtbPM48URnrFudNtw==,tVEUKMMtWy50hbruG6lSoQ==,hgNcel7/e/CAeYUwFRxnyA==,SfrWPrPaz/QR9VJbcb8lKw==
      NODE_ENV: production
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1339:1339'
 
    depends_on:
      - strapiDB
      
  ultraDB:
     
    #platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: postgres
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5439:5432'
 

volumes:
  strapi-data:
 